gitHubClientId: Ov23li36zie7xMmzF19L
gitHubClientSecret: 1967cfb4a02e862d25c32d6aabfb129331f14c1e
jwtSecret: Zjk5ZjQ0ZDEwN2U2N2Y1MjdhMzkwYjkxOGY1ZjYwOWRhNTE2MDlmNGFiNGY5NDc4ZjYyZjA3M2MzZTM0OWJiZg==

postgres:
  url: "jdbc:postgresql://localhost:5432/cleanpr_db"
  name: postgres
  password: "@Fawarda0221"

openai:
  api-key: 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