spring:
  profiles:
    active: secrets
  application:
    name: cleanPR
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: cleanpr

client:
  url: http://localhost:3000

jwt.secret.key: ${jwtSecret}

server:
  port: 8081




