spring:
  profiles:
    active: secrets
  application:
    name: cleanPR
  ai:
    openai:
      api-key: ${openai.api-key}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  datasource:
    url:  ${postgres.url}
    username: ${postgres.name}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

client:
  url: http://localhost:3000

jwt.secret.key: ${jwtSecret}

server:
  port: 8081

github:
  appId: 1953390
  key: C:\Users\fahda\Downloads\clean-pr.2025-09-15.private-key.pem

#logging:
#  level:
#    root: DEBUG




