spring:
  profiles:
    active: secrets
  application:
    name: cleanPR
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "https://03db62d1-2049-4d5d-a15a-9c68a075dd5d-00-3odpkv9xrdfc.picard.replit.dev:8081/login/oauth2/code/github"
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: cleanpr

client:
  url: https://03db62d1-2049-4d5d-a15a-9c68a075dd5d-00-3odpkv9xrdfc.picard.replit.dev:5000

jwt.secret.key: ${JWT_SECRET}

server:
  port: 8081




