spring:
  application:
    name: cleanPR
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li36zie7xMmzF19L
            client-secret: 1967cfb4a02e862d25c32d6aabfb129331f14c1e
            scope:
              - read:user
              - user:email
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: cleanpr

jwt.secret.key: Zjk5ZjQ0ZDEwN2U2N2Y1MjdhMzkwYjkxOGY1ZjYwOWRhNTE2MDlmNGFiNGY5NDc4ZjYyZjA3M2MzZTM0OWJiZg==

server:
  port: 8081




