spring.application.name: cleanPR

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li36zie7xMmzF19L
            client-secret: cea1811cba4e52ee0440e8060ea507066212052b
            scope: read:user, repo
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
