spring:
  profiles:
    active: secrets
  application:
    name: cleanPR
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  datasource:
    url: jdbc:postgresql://localhost:5432/cleanpr
    username: cleanpr
    password: "@clean-pr-gang-209"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

client:
  url: http://localhost:3000

jwt.secret.key: ${jwtSecret}

server:
  port: 8081

github:
  appId: 1953390
  key: C:\Users\fahda\Downloads\clean-pr.2025-09-15.private-key.pem




