spring:
  profiles:
    active: secrets
  application:
    name: cleanPR
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  datasource:
    url:  ${spring.datasource.url}
    username: ${spring.application.name}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5   # keep this small for Supabase free/small tiers
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update   # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

client:
  url: http://localhost:3000

jwt.secret.key: ${jwtSecret}

server:
  port: 8081

github:
  appId: 1953390
  key: C:\Users\fahda\Downloads\clean-pr.2025-09-15.private-key.pem




